repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint (bazel)
        entry: bazel test //:golangci_lint
        language: system
        pass_filenames: false
        types: [go]

      - id: shellcheck
        name: shellcheck (bazel)
        entry: bazel test //:shellcheck
        language: system
        pass_filenames: false
        types: [shell]

      - id: yamllint
        name: yamllint (bazel)
        entry: bazel test //:yamllint
        language: system
        pass_filenames: false
        types: [yaml]

      - id: actionlint
        name: actionlint (bazel)
        entry: bazel test //:actionlint
        language: system
        pass_filenames: false
        files: \.github/workflows/
